### ISSUE TITLE
It is not working in Xcode8.1

### ISSUE THREAD

**Issue by Yoginshweta** [rickytan/RTImageAssets#100]
I am trying to execute the code.But it is getting crashed in xcode8.1

Error Is : An error occured while inserting an untrusted certificate into the chain

**Comment by rickytan** [comment]
Have you unsigned the Xcode ? <https://github.com/inket/update_xcode_plugins>

**Comment by AMEstudio** [comment]
1.clean your xcode
------------
make sure your xcode is pure

2.resign your Xcode(important step)
---------------
use this way to resign your Xcode
https://github.com/XVimProject/XVim/blob/master/INSTALL_Xcode8.md
(thanks to the author of XVim)

3.download the RTImageAssets zip file
--------------
download the RTImageAssets zip file and open it's project in Xcode

4.add uuid
---------------
use the under code in terminal.
if your xcode path or name change please change the code also.

```
find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add `defaults read /Applications/Xcode.app/Contents/Info.plist DVTPlugInCompatibilityUUID`
```

5.restart your Xcode
----------------------
you will see a alert. choose load bundle on left

6.enjoy
---------------------
: )
