### ISSUE TITLE
你好，写的很牛掰，请问有打算支持xcode9么

### ISSUE THREAD

**Issue by huayingxiong** [rickytan/RTImageAssets#102]
你好，写的很牛掰，请问有打算支持xcode9么

**Comment by rickytan** [comment]
Xcode 8 以后不能支持了，Xcode 9 有新的特性可用吗？

**Comment by heyehao2008** [comment]
xcode9.0用的好好的。升级9.1就不行了。找不到xcassets。希望作者可以修复一下。这插件真的很好用。
<img width="423" alt="2017-11-14 11 11 19" src="https://user-images.githubusercontent.com/7590049/32761154-b88fde7c-c92c-11e7-9315-dc3eb13c563d.png">

**Comment by rickytan** [comment]
你的 `.xcassets` 是放到与项目同名的文件夹下吗？

**Comment by heyehao2008** [comment]
额，不是。必须是和项目同名文件夹下的才能扫描到吗？

**Comment by heyehao2008** [comment]
果然必须是在同名文件夹下才可以。OK。我新建了个同名文件夹放在里面就可以了。👍👍👍
