### ISSUE TITLE
看起来是个有点严重的问题！

### ISSUE THREAD

**Issue by LazyScream** [rickytan/RTImageAssets#103]
作者您好，当我Run起来您的专案时
Log区域打印了这段话“cannot attach to process due to System Integrity Protection”
Google了一下，发现是要把SIP的状态给关闭
但是把SIP关闭后对于电脑的风险相对就高，keychain也可以被存取了
我想询问一下是什么原因会有这个需求？

**Comment by rickytan** [comment]
Xcode 8 以后此插件不再支持，请参考 Readme.md 中的解决方案

**Comment by LazyScream** [comment]
您误会我的意思了，我已经可以使用此插件
但我现在有另外一台电脑也想安装
但我执行了这个专案并且编译得到下面的Log
我的疑问是“cannot attach to process due to System Integrity Protection”

这句LOG告诉我需要“关闭SIP”
我想询问的是为什么需要把这东西给关闭才可以开启您的专案并且编译？
无关能不能使用！

**Comment by rickytan** [comment]
这个问题我就不太清楚了，我还没在 Xcode 9 上使用过 😂
