### ISSUE TITLE
Xcode10 ,添加了UUID ，插件还是隐藏状态无法使用

### ISSUE THREAD

**Issue by fan0314** [rickytan/RTImageAssets#104]
Xcode10 ,添加了UUID ，插件还是隐藏状态无法使用

**Comment by fan0314** [comment]
![image](https://user-images.githubusercontent.com/3257387/45796938-904fb980-bcd5-11e8-81f1-2d452e98ee4d.png)

**Comment by rickytan** [comment]
**Xcode** 彻底关闭重开呢？

**Comment by ifengBigger** [comment]
我也遇到了相同的问题，请问最后怎么解决

**Comment by heyehao2008** [comment]
同样的问题，这么好用的插件，作者不打算更新了么

**Comment by heyehao2008** [comment]
彻底关闭，重启电脑都没用

**Comment by rickytan** [comment]
等我有时间。问题应该是 **Xcode 10** 某些消息通知不发了

**Comment by rickytan** [comment]
fix with https://github.com/rickytan/RTImageAssets/commit/bf4e237080c274c7f63a58e92dd7215bcf350625

**Comment by heyehao2008** [comment]
OK，又可以愉快的使用了。谢谢作者
