### ISSUE TITLE
Issue with XCode Version 6.1.1

### ISSUE THREAD

**Issue by dautovicharis** [rickytan/RTImageAssets#12]
Hello,
For some reason the images are not generated with XCode 6.1.1.
On the version XCode 5.1.1 everything works perfectly.

Thank you,
Haris

**Comment by rickytan** [comment]
Can you open the `Settings` window?

**Comment by dautovicharis** [comment]
No. When i  go to  File -> ImageAssets -> Settings  window does not appear.
I Install  RTImageAssets plugin with  PackageManager (http://alcatraz.io)

**Comment by rickytan** [comment]
#10

**Comment by dautovicharis** [comment]
Now I can see the Settings window, but after Generate Missing Assets nothing happens.

I tried with:
- https://github.com/rickytan/RTImageAssets/issues/9 (already exists in DVTPlugInCompatibilityUUIDs array)
- Create a new xcassets resource folder in the project root.

I think that for some reason the plugin can not find my xcassets folder.

**Comment by rickytan** [comment]
your `xcassets` must be in the folder with the same name of your project.

If you open `test.xcodeproj`, the `xcassets` must in `test/`

**Comment by DoctorG** [comment]
I have the same problem. I have XCAssets in same folder with name of project.   Settings window does work.  I'm just to seeing it generate any new icons.  I would love to use this great tool though?  Is there any debug or troubleshooting info I can provide to help get it working?

**Comment by rickytan** [comment]
Please build the plugin from source, `PackageManager` had some problems for now.

**Comment by dautovicharis** [comment]
It works perfectly now, thank you very much!
