### ISSUE TITLE
Slicing params

### ISSUE THREAD

**Issue by skywinder** [rickytan/RTImageAssets#14]
Where I use this tools it not copy slicing parameters for images. It will be very nice to copy that too.

**Comment by skywinder** [comment]
it means, that it's need to add in Contents.json to each image code like (with proportional numbers) :

```
      "resizing" : {
        "mode" : "9-part",
        "center" : {
          "mode" : "fill",
          "width" : 1,
          "height" : 1
        },
        "capInsets" : {
          "bottom" : 1,
          "top" : 1,
          "right" : 1,
          "left" : 1
        }
      }
```

**Comment by rickytan** [comment]
This is a new feature to be added, but I can't guarantee you the date. But your can fork this repo and help me
