### ISSUE TITLE
用1x的图生成2x和3x的没有图片。

### ISSUE THREAD

**Issue by iBenjamin** [rickytan/RTImageAssets#15]
我工程中有1x的图片，also generate non-retina和upscale 2x to 3x if NOT exists都勾选了，但是点击生成后没有相应图片。但是我将图片放到2x中再生成又可以了。

**Comment by rickytan** [comment]
不支持从 1x 生成，你不觉得很糊吗……

**Comment by iBenjamin** [comment]
好吧。。
