### ISSUE TITLE
生成图片的尺寸问题

### ISSUE THREAD

**Issue by leiyong316** [rickytan/RTImageAssets#16]
你好，假如我有个2x图片， 尺寸是640*88(像素),   生成1x后尺寸不是320*44,    3x也不是960*132    ..
这个之前有发现吗？

**Comment by rickytan** [comment]
貌似没问题啊，是 320 x 44  960 x 132

**Comment by rickytan** [comment]
貌似没问题啊，是 320 x 44  960 x 132

**Comment by rickytan** [comment]
把你用的图发上来吧

**Comment by leiyong316** [comment]
您好好， 我录了一个gif图片， 生成出来的1x和3x不是想要的尺寸。

![rtimage](https://cloud.githubusercontent.com/assets/2143362/5780059/7a3e06da-9de2-11e4-82aa-c284e9901bcd.gif)

demo工程我已传到了网盘，谢谢
http://pan.baidu.com/s/1bnhdhtt

另外我的设置是选择的iphone6，不是iphone5,  不知道这样设置有没有问题
![image](https://cloud.githubusercontent.com/assets/2143362/5780134/119bee2a-9de3-11e4-91af-9d8b0d54c2de.png)

**Comment by rickytan** [comment]
那应该就是这个问题了，iphone 6 宽 750，认为 750 为 2x ，那为 1x 是 320 ，缩放系数为 `750/320 = 2.34375`，改为 iphone 5 就好了

**Comment by leiyong316** [comment]
可以了， 感谢
