### ISSUE TITLE
有些@3x图片无法生成@2x图片

### ISSUE THREAD

**Issue by xx-li** [rickytan/RTImageAssets#21]
一直在用您的插件,很好用,非常感谢.
但是偶尔会出现一两张特殊的图片,无法生成@2x的图片(其他的图片同样操作OK).

![test11](https://cloud.githubusercontent.com/assets/5794847/6015996/6c881c2e-abb6-11e4-90e8-b0b4d06c81b7.png)

**Comment by rickytan** [comment]
特殊图片会有考虑不到的，是上面那张吗？

**Comment by xx-li** [comment]
恩, 上面那张图片生成@2x会失败.   是.png 格式的.
