### ISSUE TITLE
请问setting 中 downscale to 2x based on iPhone5 or iPhone6 能产生什么效果？

### ISSUE THREAD

**Issue by Expecto-Patronum** [rickytan/RTImageAssets#22]
RT，默认情况下是iPhone5，设置成iPhone6是否会改变尺寸压缩的比例？

由于我这边插件出现bug，setting界面无法调出，因此问一下。

**Comment by rickytan** [comment]
见 #16 

另外，无法调出 `Settings` 是 插件管理器的 bug ，请从源码安装

**Comment by Expecto-Patronum** [comment]
got it. thx~
