### ISSUE TITLE
在xcode6.2上生成的图片是黑色的

### ISSUE THREAD

**Issue by Alienchang** [rickytan/RTImageAssets#24]

**Comment by rickytan** [comment]
我这边好像没问题，请从源码更新插件。然后，如果还出现问题，请回复上传您的图片，因为有些图片的色彩空间可能不支持

**Comment by liweican1992** [comment]
我遇到了同样问题，更新至xcode6.2后部分图片生成2x图出现黑色图片情况。排除中文命名之后发现是图片的alpha通道那里为否，使用ps更改之后一切正常。

**Comment by StephenZhuang** [comment]
没有更新之前的图片和命名是对的，但是content.json里没加@2x，更新之后会出现图片变成黑色的

**Comment by rickytan** [comment]
部分图片应该是 `jpeg` 的图片吧？
