### ISSUE TITLE
突然失效了，不能生成图片，重装多次任然无效

### ISSUE THREAD

**Issue by heyehao2008** [rickytan/RTImageAssets#26]
发现这个神器后一直用的好好的，但从前天开始就失效了，点击生成没有反应，可以点开设置，各种设置，任然无效。重装，直接运行文件，用插件管理安装都试过几次了，也是无效。
而且最近没有安装其他插件，应该不是和其他插件的冲突，以前都好好的，突然就失效了。搞不清楚原因。
xcode 版本 6.1正式版
下面是我装的插件：
![default](https://cloud.githubusercontent.com/assets/7590049/6794263/bc4b0b0c-d20a-11e4-9c1d-023ae2f7edeb.png)

**Comment by rickytan** [comment]
升级到 `xcode 6.1.1` 试试呢？

**Comment by heyehao2008** [comment]
Xcode版本升级到了6.2，依然不行

**Comment by rickytan** [comment]
最新版应该已经修复了才对，我自己的是好的，这个不好办了

**Comment by rickytan** [comment]
突然发现，你的 image.asset 目录有可能没有在项目目录下

your `xcassets` must be in the folder with the same name of your project.

If you open *test.xcodeproj*, the `xcassets` must in *test/*

**Comment by heyehao2008** [comment]
嗯，确实，我的项目改了名字后就失效了，其他新建的项目正常。但是我这个改了名的项目怎么才能使用呢，我看了已经在项目目录下了啊

**Comment by rickytan** [comment]
你的   工程文件名 需要根  image.xcasset 所以的目录名一样。

你可以：

1. Xcode 打开你的工程 abcd.xcodproj
2. 重命名你的项目目录为 abcd，然后 你的 Xcode 中会变红，先不管它
3. 按 `Ctrl Shift A`
4. 生成完后，将目录名改回原来的

**Comment by heyehao2008** [comment]
嗯，谢谢，已经解决问题。我项目中使用了cocoapods。改了项目名称，忘了将xxx.xcworkspace改名，我把.xcworkspace改成了新名称就可以了
