### ISSUE TITLE
3x生成2x图片很大

### ISSUE THREAD

**Issue by LiJingBiao** [rickytan/RTImageAssets#28]
3x生成2x图片很大

**Comment by rickytan** [comment]
请用看图软件打开，看下长宽像素是多少，或者在 Finder 中选中图片，按 `Command + I`

**Comment by LiJingBiao** [comment]
![2015-04-03 3 24 15](https://cloud.githubusercontent.com/assets/5698458/6979386/99f823c4-da15-11e4-99ed-0c456b13b703.png)
![2015-04-03 3 24 33](https://cloud.githubusercontent.com/assets/5698458/6979387/99f83166-da15-11e4-9745-afb70bb98cd9.png)
