### ISSUE TITLE
3x生成2x图片很大

### ISSUE THREAD

**Issue by LiJingBiao** [rickytan/RTImageAssets#29]
刚才按错按钮了 现在我将我3X图 和生成的2X图上传给你看看
![2015-04-03 3 24 15](https://cloud.githubusercontent.com/assets/5698458/6979421/e28167d6-da15-11e4-9476-b043fd8cf5b9.png)
![2015-04-03 3 24 33](https://cloud.githubusercontent.com/assets/5698458/6979420/e2803578-da15-11e4-8dd4-260d3764a706.png)

**Comment by LiJingBiao** [comment]
原图(3X)大小是9k生成2x后变成19k了

**Comment by LiJingBiao** [comment]
我把原图上传给你，你测试看看
![test 3x](https://cloud.githubusercontent.com/assets/5698458/6979455/5c291336-da16-11e4-8b8f-a31721b3deba.png)

**Comment by rickytan** [comment]
你的意思是图片点用的磁盘空间大了是吧，这个可能与颜色空间和压缩率有关，请参照：<https://imageoptim.com/> ，可以安装他们的 `XCode` 插件 [RSImageOptimPlugin](https://github.com/yeahdongcn/RSImageOptimPlugin)
