### ISSUE TITLE
运行后没有该插件

### ISSUE THREAD

**Issue by KBvsMJ** [rickytan/RTImageAssets#33]

**Comment by rickytan** [comment]
需要重启 Xcode

**Comment by iosbsky2014** [comment]
重启了 还是没有

**Comment by rickytan** [comment]
回复一下您的 Xcode 版本号及 OS X 版号。

正常情况下，在 **Xcode** 全局菜单 `File -> ImageAssets` 下

**Comment by liurenchi** [comment]
运行，重启后也没有插件

**Comment by rickytan** [comment]
请在 `Terminal` 下运行以下命令：

    defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID

然后把输出的 `UUID` 贴上来

**Comment by liurenchi** [comment]
9F75337B-21B4-4ADC-B558-F9CADF7073A7

**Comment by rickytan** [comment]
这个 UUID 已经在列表中了，没理由啊……

总是会有各种神奇的问题出现

**Comment by westke** [comment]
最新XCode6.3.2，UUID为 E969541F-E6F9-4D25-8158-72DC3545A6C6该插件没法用了添加到里面，XCode加载bundle不成功

**Comment by rickytan** [comment]
刚更新了一版，应该已经修复 ;-)
