### ISSUE TITLE
Xcode 6.3 下显示不了插件

### ISSUE THREAD

**Issue by krisshi** [rickytan/RTImageAssets#36]
通过packet manage装的，重启过xcode
并且输入过 defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID
显示9F75337B-21B4-4ADC-B558-F9CADF7073A7

我记得我xcode没有升级到6.3前用过是好的。
作者可以查下你的Xcode 6.3行不行啊？

**Comment by rickytan** [comment]
请从源代码安装，最近 package manager 有问题

**Comment by krisshi** [comment]
xcode 6.3 运行源码报错 xib太老了

The document "IASettingsWindow.xib" could not be opened. The operation couldn’t be completed. (com.apple.InterfaceBuilder error -1.)

**Comment by rickytan** [comment]
它应该会自动转格式的吧。貌似之前有人弄好了 #34

**Comment by krisshi** [comment]
没有自动转，选择open in 是灰的 选不了，哎
![5d868e8b-73c7-429a-8e1c-427fa0f2cff6](https://cloud.githubusercontent.com/assets/5486860/7361496/e24595ce-ed8b-11e4-8067-f8029cb054e3.png)

**Comment by rickytan** [comment]
最近才升级  10.10.3 ，等我装  Xcode 6.3 看看

**Comment by krisshi** [comment]
作者10.10.3下Xcode 6.3是好的吗？ 我是各种试都不行，记得我以前10.10.3下Xcode 6.2是好的，后来卸载、重装，各种试都无效。

**Comment by rickytan** [comment]
![2015-04-29 9 21 55](https://cloud.githubusercontent.com/assets/1250207/7383443/eb65892c-ee51-11e4-8f2e-37cabd576f40.png)
貌似没问题唉

**Comment by krisshi** [comment]
好吧，不知道是什么原因，我晚上把Xcode升级到 6.3.1再试试，谢谢你！
