### ISSUE TITLE
插件在某些情况下无法使用

### ISSUE THREAD

**Issue by ihappyhacking** [rickytan/RTImageAssets#37]
不知道为何，插件在某些情况下（不明白为什么）不能使用，File菜单下，为灰色不可点击。选中Images.xcassets中的Folder/多张图片/单张图片，还是灰色不可点击。不知道有没有人遇到同样的问题？拖进去的图片是@3x的了（只有@3x）。

**Comment by rickytan** [comment]
重启 Xcode 也无效？

**Comment by roothook** [comment]
@rickytan 昨晚我关掉了Xcode，早上重新打开来，可以使用了，不清楚是为什么，之前也遇到过这个情况。
