### ISSUE TITLE
图片不能正常出来！

### ISSUE THREAD

**Issue by sxm12** [rickytan/RTImageAssets#41]
我在目录下新建了一个Supporting Files文件夹，然后把Images.xcassets放到这个文件夹下，结果下面的bundles目录就空了
NSDirectoryEnumerator *enumerator = [[NSFileManager defaultManager] enumeratorAtPath:path];
    NSString *filePath = nil;
    while (filePath = [enumerator nextObject]) {
        if ([@"xcassets" isEqualToString:filePath.pathExtension]) {
            NSString *fullPath = [path stringByAppendingPathComponent:filePath];
            NSError *error = nil;
            NSDictionary *attr = [[NSFileManager defaultManager] attributesOfItemAtPath:fullPath
                                                                                  error:&error];
            if ([attr[NSFileType] isEqualTo:NSFileTypeDirectory]) {
                [bundles addObject:fullPath];
            }
        }
    }

**Comment by rickytan** [comment]
只支持在与 项目文件同名的目录下的 image assets ，如果您打开的是 abc.xcodeproj，那么只遍历  abc/ 下的文件
