### ISSUE TITLE
xcode6.3.2下插件显示不出来

### ISSUE THREAD

**Issue by StephenZhuang** [rickytan/RTImageAssets#42]
![image](https://cloud.githubusercontent.com/assets/7381748/7739761/8b92996e-ff99-11e4-8b3a-c94f53d3cdfc.png)

DVTPlugInCompatibilityUUID 我已经添加过了，其他插件都好用的，这个插件和cocoapods插件显示不出来

**Comment by rickytan** [comment]
昨天更新了一次，还是不行吗？

**Comment by StephenZhuang** [comment]
我试试下载代码构建

**Comment by StephenZhuang** [comment]
ok了，估计package manager要升级了
