### ISSUE TITLE
最新版xcode使用时遇到问题

### ISSUE THREAD

**Issue by lucifer001** [rickytan/RTImageAssets#46]
Xcode Version 6.3.2 (6D2105) 版本下  点settings没反应，GenerateMissingAssets也没反应，求解，感谢

**Comment by rickytan** [comment]
请从源代码编译安装

**Comment by lucifer001** [comment]
是从源代码安装的，安装时会弹出提示
![2015-06-15 14 57 59](https://cloud.githubusercontent.com/assets/6162570/8154782/52558d60-1370-11e5-8214-3a584ebad3a8.png)
LoadBunles后重启xcode
GenerateMissingAssets没反应

**Comment by rickytan** [comment]
你的 image.xcasset 是在 与 项目名同名的目录下吗？

**Comment by lucifer001** [comment]
不同名  我项目改过名字但文件夹还是原来的名字
![2015-06-16 18 14 22](https://cloud.githubusercontent.com/assets/6162570/8180833/8b99463c-1453-11e5-9e09-4533be11aa52.png)

**Comment by rickytan** [comment]
此插件只处理同名目录下的，因为不同名的可能是其他项目的图片文件，你可以在 Xcode 中打开项目，然后改目录名，这时项目会变红，先不管它，然后按 ctrl+shift+a，再将目录名改回

**Comment by ericdream** [comment]
不 支持最新版本的吗 xcode6.4

**Comment by rickytan** [comment]
支持的

**Comment by ericdream** [comment]
谢谢 终于搞定了  不知道为什么 我先使用命令安装 没法使用的 然后使用源代码安装还是不能使用 最后全卸载了在使用源代码安装 就ok了
