### ISSUE TITLE
Doesn't work at last Xcode 6.3.2 (6D2105)

### ISSUE THREAD

**Issue by Just-** [rickytan/RTImageAssets#50]
Hi, thank you for this nice plugin. 
Unfortunately after installing 6.3.2 plugin generates nothing. I tried installing with Plugin Manager and also build from last commit in master f6b13a6b88182b43af76a8f43b9a111a0e065881. All have the same effects.

**Comment by rickytan** [comment]
Is your project name the same as the folder name which contains your `Image.xcassets` ?

**Comment by Just-** [comment]
Just rename it to match and all works well! Thanks! :+1:
