### ISSUE TITLE
Xcode 6.4 支持

### ISSUE THREAD

**Issue by leiyong316** [rickytan/RTImageAssets#54]
@rickytan  你好， 使用xcode6.4插件失效，能不能修复后加入对Package Manager的支持

**Comment by rickytan** [comment]
#9

**Comment by RexDu** [comment]
编译安装后 重启 Xcode 后有没有“弹窗Load Bundle”    在Xcode - > view 里面也没有 ImageAssets 这项 尝试了很多次 始终不行   Xcode Version 6.4 (6E35b)  辛苦您了

**Comment by rickytan** [comment]
在 `Terminal` 下运行以下命令：

    defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID

然后把输出的 `UUID` 贴上来

**Comment by rickytan** [comment]
已经添加了，请从最新的源代码编译安装

**Comment by RexDu** [comment]
UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90

**Comment by rickytan** [comment]
已经添加
