### ISSUE TITLE
PNG素材和PDF素材混用时会将PDF素材文件名重命名为xxx@(null).pdf

### ISSUE THREAD

**Issue by Sunnyyoung** [rickytan/RTImageAssets#56]
如题

**Comment by rickytan** [comment]
您的 pdf 文件能放上来一个吗？

**Comment by Sunnyyoung** [comment]
@rickytan sorry, github无法上传pdf，发到你的邮箱了，感谢

**Comment by rickytan** [comment]
Copy ，有空了试试！

**Comment by rickytan** [comment]
Sorry for the super delay...已更新

话说下图才是矢量图的正确使用方式：
![2015-07-24 10 38 02](https://cloud.githubusercontent.com/assets/1250207/8866539/42d0af7a-31f0-11e5-8371-bcab92c4db3f.png)
