### ISSUE TITLE
该插件在Xcode 6.4上运行无法转换

### ISSUE THREAD

**Issue by 345928650** [rickytan/RTImageAssets#57]
在Xcode 6.4版本上运行时3X图片无法转化出2x的图片，但是设置后可以成功转换成1X的图片，期待更新；

**Comment by rickytan** [comment]
还没用到 xcode 6.4 ，所以不太清楚

**Comment by peter35** [comment]
Xcode 6.4  不行

**Comment by rickytan** [comment]
请删除重新编译安装，打开 Xcode 时，如有提示选  `Load Bundles`，我这边貌似没问题
![2015-07-12 10 33 20](https://cloud.githubusercontent.com/assets/1250207/8636093/b8ccb99e-2881-11e5-8a39-4567066f5107.png)

**Comment by peter35** [comment]
http://blog.csdn.net/xiaoliuxingzi/article/details/46889429
