### ISSUE TITLE
Can't find any .xcassets bundle

### ISSUE THREAD

**Issue by mikeRozen** [rickytan/RTImageAssets#58]
I receive the following error:
![screen shot 2015-07-31 at 22 37 46](https://cloud.githubusercontent.com/assets/11506268/9015911/456f552a-37d5-11e5-843d-a9db704b883f.png)
I tried to create a different .xcasset in different place but still have the same Error.(it happens when I try to generate missing assets)
Can you please help me with that?
Tnx A Lot.

**Comment by rickytan** [comment]
Is your Assets Catalog in the folder the same name with the project ?

If your project is `abc.xcodeproj`, and the assets must be in the `abc` folder
