### ISSUE TITLE
此版本无法设置是否iPhone6

### ISSUE THREAD

**Issue by lYcHeeM** [rickytan/RTImageAssets#59]
一个月前使用RTImageAssets的时候，记得Setting界面有个“iPhone6”的CheckBox，但是前些天更新后就没有了![af1040e8-eb61-4172-add9-d62348450dc8](https://cloud.githubusercontent.com/assets/8675472/9058024/af822890-3ad0-11e5-869f-a4c435bd26b8.png)
，看了RTImageAssets的源代码，发现生成3种规格的图片都会判断是否有iPhone6这个选项![e0496f8e-47e5-49cf-bd08-28fa61d262f6](https://cloud.githubusercontent.com/assets/8675472/9058015/99c5b76a-3ad0-11e5-8f05-871ab7d0ae6a.png)，这个选项会决定按何种比例生成图片。不知这是不是个bug，我现在如果想按照1.5的缩小比例生成@2x，就必须修改RTImageAssets的源代码并重新编译生成一份Xcode插件。

**Comment by rickytan** [comment]
这个，因为 iphone 5 和 iphone 6 都是 2x 图片，这个选项其实没什么用，反而会误导，所以隐藏了。

您可以打开源码，找到 SettingsWindow.xib ，把 `Hidden` 去掉，跟 iOS 开发一样
