### ISSUE TITLE
捐助按钮就是一图片么..

### ISSUE THREAD

**Issue by GWesley** [rickytan/RTImageAssets#61]
为啥不放个支付宝二维码呢 ？

**Comment by rickytan** [comment]
Just for Fun :smile:  

您真的要捐么？ :heart_eyes:

**Comment by rickytan** [comment]
😃

**Comment by langyufei** [comment]
我也是要捐的时候发现了这个问题...
不过xcassets文件一定要在工程名的文件夹下让我很头疼啊!

**Comment by rickytan** [comment]
因为您可能用到第三方库，一般放在工程名文件夹外的 Vendors 下，我不想破坏它的完整性

**Comment by langyufei** [comment]
哦，今天又试了一下捐助按钮，看来你可以关闭这个问题了 :) 不过因为工程需要，我只能自己修改重编译插件以便能找到不在工程名文件夹下的xcassets文件。建议加入一个设置面板让用户指定路径什么的，我不要开新的issue了，大家都很忙，建议而已。Enjoy your coffee!

**Comment by rickytan** [comment]
Copy that, thanks ! :smile:
