### ISSUE TITLE
Xcode6.4将3x转换时候出现错误提示

### ISSUE THREAD

**Issue by suifens** [rickytan/RTImageAssets#62]
出现这个提示有什么解决办法
![d8c4386b-ee61-4489-a58e-afce147809f3](https://cloud.githubusercontent.com/assets/5051457/9597152/48faaaba-50b1-11e5-8226-49c734717eec.png)

**Comment by rickytan** [comment]
将您的  `.xcasset` 放到与项目名同名的目录下，如 `abcd.xcodeproj` ，那么放到  `abcd` 目录下
