### ISSUE TITLE
Image @2x larger than @3x

### ISSUE THREAD

**Issue by JonyMateos** [rickytan/RTImageAssets#68]
I have generated @2x image from @3x image exported from Illustrator. 
@3x has size 500bytes and @2x has size 2kb.  
Also I tried ImageOptim and the result has been the same.

**Comment by rickytan** [comment]
In fact, all `PNG` files will be optimized automatically by **Xcode** while archiving, I don't think this would be a problem.

**Comment by leenat** [comment]
Yes, even when you use Preview mac app to resize image @2x appears to be larger in size as compared to @3x size

**Comment by JonyMateos** [comment]
Thank you both :+1:
