### ISSUE TITLE
XCODE 7.1中不能使用

### ISSUE THREAD

**Issue by luocanfly** [rickytan/RTImageAssets#72]
XCODE 7.1中不能使用 
出现这个 : Null passed to a callee that requires a non-null argument

**Comment by rickytan** [comment]
自己编译时的 warning ?

**Comment by luocanfly** [comment]
嗯 编译是success，这是个警告，可是xcode7中确实编译好了 找不到这个插件。我的系统是mac os el capitan

**Comment by hh1myfei** [comment]
现在在 xCode 7.x + OS X EL Capitan 上面是没法用的，在xCode 6.x 的时候用的好好的，所以只让美工做了@3x的图，现在不能用了，而且要快要上线了，求有没有mac 软件可以批量或快速的把@3x 生成@2x的图片，最后弱弱的问一句，啥时候更新啊，大神。please

**Comment by rickytan** [comment]
找不到插件，你需要找到 插件目录，删除重新安装，启动 **Xcode** 时选  Load Bundle

**Comment by rickytan** [comment]
其他软件我已经列在 **README.md** 里了 @hh1myfei

**Comment by hh1myfei** [comment]
感激，好用了，在~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ 删除掉，重新编译，然后选load bundle 可以使用了。thank you very much

**Comment by luocanfly** [comment]
我的系统没~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/  奇了怪，我升级的最新mac

**Comment by rickytan** [comment]
编译运行下试试呢？Command + R

**Comment by ty19891833** [comment]
删掉了，重新编译，可是根本就没有弹出框了

**Comment by rickytan** [comment]
重启 **Xcode** 才生效 @ty19891833
