### ISSUE TITLE
Cannot work in xcode 7.2

### ISSUE THREAD

**Issue by WarnWang** [rickytan/RTImageAssets#77]
I updated to xcode 7.2 today, then I cannot find this button
![image](https://cloud.githubusercontent.com/assets/13817660/11680468/7523350a-9e93-11e5-91dd-91ab7ed062e6.png)

**Comment by stefanomondino** [comment]
me neither

**Comment by beiliubei** [comment]
+1

**Comment by cyqluowang** [comment]
+1

**Comment by nizenyang** [comment]
+1

**Comment by mewehk** [comment]
+1

**Comment by balkarov** [comment]
1) Download RTImageAssets zip from github
2) Open info.plist 
3) add new string item F41BD31E-2683-44B8-AE7F-5F09E919790E to DVTPlugInCompatibilityUUIDs
4) Save info.plist . Open RTImageAssets.xcodeproj and run
5) Restart xcode -> load bundles

**Comment by wanghaolyj** [comment]
+1

**Comment by NSDeveloper** [comment]
Cannot work in Xcode xxx problem,see this : http://stackoverflow.com/questions/30361228/

**Comment by beiliubei** [comment]
@balkarov  work fine

**Comment by Ged2323** [comment]
I added :
3) add new string item F41BD31E-2683-44B8-AE7F-5F09E919790E to DVTPlugInCompatibilityUUIDs

and followed the steps.  The menu item is showing up but it's not creating the new images.

**Comment by balkarov** [comment]
A Xcode plugin to automatically generate @2x, @1x image from @3x image for you, or upscale to @3x from @2x. 

Plugin not work with launchimage.

**Comment by Ged2323** [comment]
Ok so it seems to be fully working.

**Comment by rickytan** [comment]
Thanks, @NSDeveloper :+1:

**Comment by rickytan** [comment]
For lauchimage, please see #76  @balkarov

**Comment by rickytan** [comment]
updated
