### ISSUE TITLE
3x生成2x，2x图上传到https://tinypng.com/ 压缩图片，颜色会变深

### ISSUE THREAD

**Issue by 275080225** [rickytan/RTImageAssets#81]
3x生成2x，2x图上传到https://tinypng.com/ 压缩图片，颜色会变深；3x图确是正常的，这是为啥？
![a80618c7-1878-4311-81a1-4291321bc2b7](https://cloud.githubusercontent.com/assets/5517520/12344406/937f2472-bb77-11e5-87c9-9d2a13736b5f.png)

**Comment by rickytan** [comment]
为什么 close 了？

**Comment by 275080225** [comment]
我删除2x图重新删除就可以了，可能是图片压缩导致的

**Comment by rickytan** [comment]
<img width="612" alt="2016-01-15 17 27 32" src="https://cloud.githubusercontent.com/assets/1250207/12349782/53314b80-bbad-11e5-81be-3be0e91a6580.png">
大多数情况下，用不到 tinypng，你开启下 Catalog 优化好了
