### ISSUE TITLE
自动生成的AppIcon在安装后四周有黑边

### ISSUE THREAD

**Issue by ghost** [rickytan/RTImageAssets#85]
如题所示，请问是否是图片的问题。

**Comment by rickytan** [comment]
图片发一下可以吗？

**Comment by linwengong** [comment]
![itunesartwork 2x](https://cloud.githubusercontent.com/assets/10017871/13466648/e3ba0ac8-e0d5-11e5-9449-c893c3534d38.png)

**Comment by rickytan** [comment]
貌似没问题呃……

<img width="783" alt="2016-03-04 9 26 05" src="https://cloud.githubusercontent.com/assets/1250207/13528257/bfe6a2e8-e24f-11e5-971e-ea003940d529.png">

**Comment by linwengong** [comment]
我知道为什么了，因为我这个图标的圆角比标准的大，所以会有黑边。建议在制作AppIcon的功能上加一项功能：如果用的图片为方形，那么自动裁剪圆角然后生成图标。

**Comment by rickytan** [comment]
圆角图标最终生成到 app 上是会自动有。另外，程序中的占位图的半径可以为作参考：
![](https://github.com/rickytan/RTImageAssets/blob/master/RTImageAssets/Appicon%402x.png?raw=true)
