### ISSUE TITLE
操作的时候能不能只针对选中的 set

### ISSUE THREAD

**Issue by wangbiye** [rickytan/RTImageAssets#88]
有的 image set 不像生成2x 的图片, 结果点一次全都生成了, 图片多了安装包大了不少

**Comment by rickytan** [comment]
如果不要生成 2x 的是多数，目前只能手动生成少数的那几个 2x 了 :joy: 

如果要生成 2x 的是多数，你可以生成后再删 :joy:

**Comment by wangbiye** [comment]
😱😱😱😱😱😱
