### ISSUE TITLE
Xcode 6.1.1 安装插件重启后找不到插件菜单

### ISSUE THREAD

**Issue by codetalks-new** [rickytan/RTImageAssets#9]
RT:
选中图片按 Ctrl + Shift + A 也没有反应.

**Comment by leiyong316** [comment]
7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90

**Comment by leiyong316** [comment]
@rickytan  我在本地已经加了， 你可以加上后提交到package manager
