### ISSUE TITLE
Xcode 7.3 无法正常使用

### ISSUE THREAD

**Issue by SuperDannyBoy** [rickytan/RTImageAssets#93]
插件确实能够打开，但是将图片拖进去之后却无法生成。

**Comment by rickytan** [comment]
点 **Generate** 无效么？

**Comment by SuperDannyBoy** [comment]
![0a8bf2e6-ef07-468b-931b-0e1151e27ba2](https://cloud.githubusercontent.com/assets/5237197/14977777/a66674b4-1149-11e6-8a67-1589e96d6ac6.png)
@rickytan 是的，点击没反应，另外左侧两个选项也没有可以选择。

**Comment by rickytan** [comment]
你需要在 **.xcassets** 中添加  **.appicon**

**Comment by rickytan** [comment]
也有可能，你的 **.xcassets** 不在与项目同名的目录下

**Comment by rickytan** [comment]
![2016-05-03 4 27 19](https://cloud.githubusercontent.com/assets/1250207/14978086/f108f0ee-114b-11e6-9b54-2b3652c384b1.png)
