### ISSUE TITLE
iOS 7 -iOS8

### ISSUE THREAD

**Issue by Luccifer** [rickytan/RTImageAssets#95]
Actually when using auto-mod, the device can't find the autogenerated slices and only black images(white/transparent) appears

If we use manual drag-n-drop slices into assets - everything okey, but if using plugin on iOS 7 and iOS 8 we can achieve the following:
[CUIThemeRendition newImageFromCSIDataSlice:ofBitmap: usingColorspace:] Unsupported pixel format in CSI got 4
Unable to create unsliced image from csi bitmap data.

**Comment by rickytan** [comment]
I think you have to change the color space of your images
