### ISSUE TITLE
Support Xcode 8 

### ISSUE THREAD

**Issue by embassem** [rickytan/RTImageAssets#98]
Support Xcode 8

**Comment by rickytan** [comment]
~~Xcode 8~~ is no longer supported, here is a [Solution](https://github.com/fpg1503/MakeXcodeGr8Again), use at your own risk

**Comment by balkarov** [comment]
I unsign xcode 8, other plugins work, but this plugin not working

**Comment by rickytan** [comment]
I haven't upgrade to Xcode 8 yet, please tell me the `UUID`:

    defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID

**Comment by balkarov** [comment]
I can tell you today later. Now I have not Computer near. But you can get UUID for Xcode 8.0 and 8.1 from Alcatraz 
Look 
 		<string>8A66E736-A720-4B3C-92F1-33D9962C69DF</string>
		<string>65C57D32-1E9B-44B8-8C04-A27BA7AAE2C4</string>

**Comment by balkarov** [comment]
Nice, last commit is work for Xcode 8. Thanks!
If somebody need how make Xcode 8 + plugins I use this library
https://github.com/inket/update_xcode_plugins
